### PR TITLE
SEARCH-1260: Update Solr memory setting on AWS

### PR DESCRIPTION
**Pull request by tunaaksoy**

### CODE REVIEW

**Comment by michaelsuzukisagi** [comment]
LGTM

**Comment by tunaaksoy** [comment]
The memory update will be done in the acs-deployment-aws project.

**Comment by tunaaksoy** [comment]
Do you want to apply that as the default for all deployments (even if you deploy all the application on one node)?

**Comment by tunaaksoy** [comment]
Then doing the change in the helm chart won't make sense. You can use the helm chart and deploy ACS with ASS on a KOPS cluster where you don't necessarily have a dedicated worker for ASS.

**Comment by michaelsuzukisagi** [comment]
I did not say where to make the changes, I remarked on the fact the memory change is not visible for this ticket. The work for this ticket should cover the memory change. Updating the artifact to 1.3-rc should have been done by another ticket?

**Comment by tunaaksoy** [comment]
We need to update the artifact to 1.3.0-RC1 so that we have the Java 11 changes. Then this helm chart will be released. And another PR will be created for acs-deployment project so that it can pull the latest search-helm chart which will bring the Java 11 updates. And lastly the acs-deployment-aws project will be updated to reflect the memory settings changes. To be able to close the ticket we need 3 PRs and 2 releases. This is the first PR.
My question above was about the default memory settings if ASS is not deployed on AWS. I'll keep that as it is.

**Pull request merged**
